// vishlabs-client/src/components/ProjectsHero.tsx
import styles from './ProjectsHero.module.scss';

export default function ProjectsHero() {
  return (
    <div className={styles['hero-container']}>
      <div className={styles['hero-bg']}>
        <video
          autoPlay
          muted
          loop
          className={styles['background-video']}
          preload="auto"
        >
          <source src="/videos/AboutLandingVideo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>

      <div className={styles['hero-content']}>
        <h1>My Projects</h1>
        <a
          href="https://github.com/vishnuGops"
          className={styles['hero-btn']}
          target="_blank"
          rel="noopener noreferrer"
        >
          Visit my Github
        </a>
      </div>
    </div>
  );
}

// dashboard-client/src/app/components/projects-hero/projects-hero.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-projects-hero',
  standalone: true,
  imports: [RouterModule, MatButtonModule, MatCardModule],
  templateUrl: './projects-hero.component.html',
  styleUrl: './projects-hero.component.scss'
})
export class ProjectsHeroComponent {

}

<div class="hero-container">
  <!-- Background Video -->
  <div class="hero-bg">
    <video
      autoplay
      loop
      onloadedmetadata="this.muted=true"
      class="background-video"
      preload="auto"
    >
      <source src="/videos/AboutLandingVideo.mp4" type="video/mp4" />
      Your browser does not support the video tag.
    </video>
  </div>

  <!-- Hero Content -->
  <mat-card class="hero-content">
    <h1>My Projects</h1>
    <!-- Updated Button -->
    <a href="https://github.com/vishnuGops" class="hero-btn">Visit my Github</a>
  </mat-card>
</div>
