// vishlabs-client/src/components/ProjectsInfo.tsx
import styles from './ProjectsInfo.module.scss';
import { projectsData } from '../data/projects';

export default function ProjectsInfo() {
  // Helper to group data into rows of 3
  const rows = [];
  for (let i = 0; i < projectsData.length; i += 3) {
    rows.push(projectsData.slice(i, i + 3));
  }

  return (
    <div className={styles['info-container']}>
      {rows.map((row, rowIndex) => (
        <div key={rowIndex} className={styles['projects-row']}>
          {row.map((project, index) => (
            <div key={index} className={styles['experience-content']}>
              <div className={styles['navbar-logo']}>
                <a
                  href={project.githubLink}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <img
                    src={project.image}
                    alt={project.name + ' Logo'}
                    className={styles.logo}
                  />
                </a>
              </div>
              <h1>{project.name}</h1>
              <a
                href={project.githubLink}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="GitHub"
              >
                <i className={`fab fa-github ${styles['git-icon']}`}></i>
              </a>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}

// dashboard-client/src/app/components/projects-info/projects-info.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';

interface Projects {
  name: string;
  description: string;
  githubLink: string;
  image: string;
}

@Component({
  selector: 'app-projects-info',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './projects-info.component.html',
  styleUrls: ['./projects-info.component.scss']
})
export class ProjectsInfoComponent implements OnInit{
  projectsData: Projects[][] = []; // Array of arrays for rows

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http.get<{ projects: Projects[] }>('/json/projects-data.json').subscribe(data => {
      const projects = data.projects;
      this.projectsData = this.groupIntoRows(projects,3);
    });
  }

  private groupIntoRows(array: Projects[], size: number): Projects[][] {
    const rows: Projects[][] = [];
    for (let i = 0; i < array.length; i += size) {
      rows.push(array.slice(i, i + size));
    }
    return rows;
  }

}

<div class="info-container">
  <div class="projects-row" *ngFor="let projectRow of projectsData">
    <div class="experience-content" *ngFor="let project of projectRow">
      <div class="navbar-logo">
        <a
          [href]="project.githubLink"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img
            [src]="project.image"
            [alt]="project.name + ' Logo'"
            class="logo"
          />
        </a>
      </div>
      <h1>{{ project.name }}</h1>
      <!-- <h2>{{ project.description }}</h2> -->
      <a
        [href]="project.githubLink"
        target="_blank"
        rel="noopener"
        aria-label="Twitter"
      >
        <i class="fab fa-github git-icon"></i>
      </a>
    </div>
  </div>
</div>
