// vishlabs-client/src/components/AboutHero.tsx
import Link from 'next/link';
import styles from './AboutHero.module.scss';

export default function AboutHero() {
  return (
    <div className={styles['hero-container']}>
      <div className={styles['hero-bg']}>
        <video
          autoPlay
          muted
          loop
          className={styles['background-video']}
          preload="auto"
        >
          <source src="/videos/AboutLandingVideo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>

      <div className={styles['hero-content']}>
        <h1>About me</h1>
        <p>I am Vishnu</p>
        <p>Senior Software Engineer</p>
        <Link href="/contact" className={styles['hero-btn']}>
          Get in touch with me
        </Link>
      </div>
    </div>
  );
}

// dashboard-client/src/app/components/about-hero/about-hero.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-about-hero',
  standalone: true,
  imports: [RouterModule, MatButtonModule, MatCardModule],
  templateUrl: './about-hero.component.html',
  styleUrl: './about-hero.component.scss',
})
export class AboutHeroComponent {}

<div class="hero-container mat-elevation-z4">
  <!-- Background Video -->
  <div class="hero-bg">
    <video
      autoplay
      loop
      onloadedmetadata="this.muted=true"
      class="background-video"
      preload="auto"
    >
      <source src="/videos/aboutHero_Video.mp4" type="video/mp4" />
      Your browser does not support the video tag.
    </video>
  </div>

  <!-- Hero Content -->
  <mat-card class="hero-content">
    <h1>About me</h1>
    <p>I am Vishnu</p>
    <p>Senior Software Engineer</p>
    <!-- Updated Button -->
    <a href="/contact" class="hero-btn"> Get in touch with me </a>
  </mat-card>
</div>
