// dashboard-client/src/app/components/about-experience/about-experience.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';

interface Experience {
  company: string;
  url: string;
  logo: string;
  position: string;
  location: string;
  period: string;
  responsibilities: string[];
}

@Component({
  selector: 'app-about-experience',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './about-experience.component.html',
  styleUrls: ['./about-experience.component.scss']
})
export class AboutExperienceComponent implements OnInit {
  experienceData: Experience[][] = []; // Array of arrays for rows

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http.get<{ experience: Experience[] }>('/json/experience-data.json').subscribe(data => {
      // Group experiences into rows of 2
      const experiences = data.experience;
      this.experienceData = this.groupIntoRows(experiences, 2);
    });
  }

  private groupIntoRows(array: Experience[], size: number): Experience[][] {
    const rows: Experience[][] = [];
    for (let i = 0; i < array.length; i += size) {
      rows.push(array.slice(i, i + size));
    }
    return rows;
  }
}

<div class="info-container">
  <h1>Experience</h1>
  <div class="experience-row" *ngFor="let row of experienceData">
    <div class="experience-content" *ngFor="let exp of row">
      <div class="navbar-logo">
        <a [href]="exp.url" target="_blank" rel="noopener noreferrer">
          <img [src]="exp.logo" [alt]="exp.company + ' Logo'" class="logo" />
        </a>
      </div>
      <h1>{{ exp.company }}</h1>
      <h2>{{ exp.position }}</h2>
      <h3>{{ exp.location }}</h3>
      <h4>{{ exp.period }}</h4>
      <ul>
        <li *ngFor="let responsibility of exp.responsibilities">
          {{ responsibility }}
        </li>
      </ul>
    </div>
  </div>
</div>

// vishlabs-client/src/components/AboutExperience.tsx
import styles from './AboutExperience.module.scss';
import { experienceData } from '../data/experience';

export default function AboutExperience() {
  // Helper to group data into rows of 2
  const rows = [];
  for (let i = 0; i < experienceData.length; i += 2) {
    rows.push(experienceData.slice(i, i + 2));
  }

  return (
    <div className={styles['info-container']}>
      <h1>Experience</h1>
      {rows.map((row, rowIndex) => (
        <div key={rowIndex} className={styles['experience-row']}>
          {row.map((exp, index) => (
            <div key={index} className={styles['experience-content']}>
              <div className={styles['navbar-logo']}>
                <a href={exp.url} target="_blank" rel="noopener noreferrer">
                  <img
                    src={exp.logo}
                    alt={exp.company + ' Logo'}
                    className={styles.logo}
                  />
                </a>
              </div>
              <h1>{exp.company}</h1>
              <h2>{exp.position}</h2>
              <h3>{exp.location}</h3>
              <h4>{exp.period}</h4>
              <ul>
                {exp.responsibilities.map((resp, i) => (
                  <li key={i}>{resp}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}
