// dashboard-client/src/app/components/about-education/about-education.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';

interface Education {
  institution: string;
  logo: string;
  url: string;
  period: string;
  location: string;
  courses: string[];
}

@Component({
  selector: 'app-about-education',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './about-education.component.html',
  styleUrls: ['./about-education.component.scss']
})

export class AboutEducationComponent implements OnInit {
  educationData: Education[] = [];

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http.get<{ education: Education[] }>('/education-data.json').subscribe(data => {
      this.educationData = data.education;
    });
  }

  downloadResume(): void {
    const link = document.createElement('a');
    link.href = '/pdf/Vishnu_Resume.pdf'; // Path to your resume PDF
    link.download = 'Vishnu_Resume.pdf';
    link.click();
  }
}

<div class="info-container">
  <h1>Education</h1>
  <div class="experience-row">
    <div class="experience-content" *ngFor="let edu of educationData">
      <div class="navbar-logo">
        <a [href]="edu.url" target="_blank" rel="noopener noreferrer">
          <img
            [src]="edu.logo"
            [alt]="edu.institution + ' Logo'"
            class="logo"
          />
        </a>
      </div>
      <h1>{{ edu.institution }}</h1>
      <h2>{{ edu.period }}</h2>
      <h3>{{ edu.location }}</h3>
      <h4>Relevant Courses</h4>
      <ul>
        <li *ngFor="let course of edu.courses">{{ course }}</li>
      </ul>
    </div>
  </div>
  <div class="resume-download">
    <button class="button-element big fontBig" (click)="downloadResume()">
      Download My Resume
    </button>
  </div>
</div>

// vishlabs-client/src/components/AboutEducation.tsx
'use client';
import styles from './AboutEducation.module.scss';
import { educationData } from '../data/education';

export default function AboutEducation() {
  const downloadResume = () => {
    const link = document.createElement('a');
    link.href = '/pdf/Vishnu_Resume.pdf';
    link.download = 'Vishnu_Resume.pdf';
    link.click();
  };

  return (
    <div className={styles['info-container']}>
      <h1>Education</h1>
      <div className={styles['experience-row']}>
        {educationData.map((edu, index) => (
          <div key={index} className={styles['experience-content']}>
            <div className={styles['navbar-logo']}>
              <a href={edu.url} target="_blank" rel="noopener noreferrer">
                <img
                  src={edu.logo}
                  alt={edu.institution + ' Logo'}
                  className={styles.logo}
                />
              </a>
            </div>
            <h1>{edu.institution}</h1>
            <h2>{edu.period}</h2>
            <h3>{edu.location}</h3>
            <h4>Relevant Courses</h4>
            <ul>
              {edu.courses.map((course, i) => (
                <li key={i}>{course}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className={styles['resume-download']}>
        <button
          className={`${styles['button-element']} ${styles.big} ${styles.fontBig}`}
          onClick={downloadResume}
        >
          Download My Resume
        </button>
      </div>
    </div>
  );
}
