// dashboard-client/src/app/components/contact-info/contact-info.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';

interface ContactLink {
  url: string;
  icon: string;
  label: string;
  text: string;
}

interface ContactPair {
  first: ContactLink;
  second?: ContactLink;
}

@Component({
  selector: 'app-contact-info',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './contact-info.component.html',
  styleUrl: './contact-info.component.scss',
})
export class ContactInfoComponent implements OnInit {
  contactPairs: ContactPair[] = [];
  protected Math = Math;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.http
      .get<{ contactLinks: ContactLink[] }>('/json/contact-links.json')
      .subscribe((data) => {
        // Group links into pairs
        for (let i = 0; i < data.contactLinks.length; i += 2) {
          this.contactPairs.push({
            first: data.contactLinks[i],
            second: data.contactLinks[i + 1],
          });
        }
      });
  }
}

<div class="info-container">
  <h1>Find Me Here</h1>
  <div class="contact-row">
    <a
      href="https://linkedin.com/in/vishnugops"
      target="_blank"
      rel="noopener"
      aria-label="Linkedin"
    >
      <div class="contact-content">
        <i class="fab fa-linkedin logo"></i>
        <h2>Vishnugops</h2>
      </div>
    </a>
    <a
      href="https://x.com/vishnu_gops"
      target="_blank"
      rel="noopener"
      aria-label="Twitter"
    >
      <div class="contact-content">
        <i class="fab fa-twitter logo"></i>
        <h2>Vishnu_gops</h2>
      </div>
    </a>
    <a
      href="mailto:vishnugrajan14@gmail.com?subject=Hello Vishnu!&body=I wanted to get in touch with you."
      rel="noopener"
      aria-label="Email"
    >
      <div class="contact-content">
        <i class="fas fa-envelope logo"></i>
        <h2>vishnugrajan14</h2>
      </div>
    </a>
  </div>
  <div class="contact-row">
    <a
      href="https://instagram.com/vishnugops"
      target="_blank"
      rel="noopener"
      aria-label="Instagram"
    >
      <div class="contact-content">
        <i class="fab fa-instagram logo"></i>

        <h2>VishnuGops</h2>
      </div>
    </a>
    <a
      href="https://www.youtube.com/channel/UCqRp3VPHZ_sW4Rxkd2Rx51A"
      target="_blank"
      rel="noopener"
      aria-label="YouTube"
    >
      <div class="contact-content">
        <i class="fab fa-youtube logo"></i>
        <h2>Vishnu Gopal</h2>
      </div>
    </a>
    <a
      href="https://instagram.com/vish_you_were_there"
      target="_blank"
      rel="noopener"
      aria-label="Instagram"
    >
      <div class="contact-content">
        <i class="fab fa-instagram logo"></i>
        <h2>vish_you_were_there</h2>
      </div>
    </a>
  </div>
</div>

// vishlabs-client/src/components/ContactInfo.tsx
import styles from './ContactInfo.module.scss';
import { contactLinks } from '../data/contact';

export default function ContactInfo() {
  // Helper to group data into pairs
  const pairs = [];
  for (let i = 0; i < contactLinks.length; i += 2) {
    pairs.push({
      first: contactLinks[i],
      second: contactLinks[i + 1],
    });
  }

  return (
    <div className={styles['info-container']}>
      <h1>Find Me Here</h1>
      {pairs.map((pair, index) => (
        <div key={index} className={styles['contact-row']}>
          <a
            href={pair.first.url}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={pair.first.label}
          >
            <div className={styles['contact-content']}>
              <i className={`${pair.first.icon} ${styles.logo}`}></i>
              <h2>{pair.first.text}</h2>
            </div>
          </a>
          {pair.second && (
            <a
              href={pair.second.url}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={pair.second.label}
            >
              <div className={styles['contact-content']}>
                <i className={`${pair.second.icon} ${styles.logo}`}></i>
                <h2>{pair.second.text}</h2>
              </div>
            </a>
          )}
        </div>
      ))}
    </div>
  );
}
