// dashboard-client/src/app/components/contact-hero/contact-hero.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-contact-hero',
  standalone: true,
  imports: [RouterModule, MatButtonModule, MatCardModule],
  templateUrl: './contact-hero.component.html',
  styleUrl: './contact-hero.component.scss',
})
export class ContactHeroComponent {}

<div class="hero-container mat-elevation-z4">
    <!-- Background Video -->
    <div class="hero-bg">
      <video autoplay muted loop class="background-video">
        <source src="/aboutHero_Video.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
    </div>
  
    <!-- Hero Content -->
    <mat-card class="hero-content">
      <h1>Get in touch with me</h1>
      <p>I am Vishnu</p>
      <p>Senior Software Engineer</p>
      <!-- Updated Button -->
      <a href="/contact" class="hero-btn big fontBig">
        Get in touch with me
      </a>
    </mat-card>
  </div>

// vishlabs-client/src/components/ContactHero.tsx
import styles from './ContactHero.module.scss';

export default function ContactHero() {
  return (
    <div className={styles['hero-container']}>
      <div className={styles['hero-bg']}>
        <video
          autoPlay
          muted
          loop
          className={styles['background-video']}
          preload="auto"
        >
          <source src="/videos/ContactLandingVideo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>

      <div className={styles['hero-content']}>
        <h1>Get in touch with me</h1>
      </div>
    </div>
  );
}
