// dashboard-client/src/app/components/landing-hero/landing-hero.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-landing-hero',
  standalone: true,
  imports: [RouterModule, MatButtonModule, MatCardModule],
  templateUrl: './landing-hero.component.html',
  styleUrls: ['./landing-hero.component.scss'],
})
export class LandingHeroComponent {}

<div class="hero-container mat-elevation-z4">
  <!-- Background Video -->
  <div class="hero-bg">
    <video autoplay muted loop class="background-video">
      <source src="/landingHero_Video.mp4" type="video/mp4" />
      Your browser does not support the video tag.
    </video>
  </div>

  <!-- Hero Content -->
  <mat-card class="hero-content">
    <h1>Welcome to My World</h1>
    <p>I am Vishnu</p>
    <p>Senior Software Engineer</p>
    <!-- Updated Button -->
    <a href="/about" class="hero-btn big fontBig">
      Get in touch with me
    </a>
  </mat-card>
</div>

// vishlabs-client/src/components/LandingHero.tsx
import Link from 'next/link';
import styles from './LandingHero.module.scss';

export default function LandingHero() {
  return (
    <div className={styles['hero-container']}>
      <div className={styles['hero-bg']}>
        <video
          autoPlay
          muted
          loop
          className={styles['background-video']}
          preload="auto"
        >
          <source src="/videos/LandingVideo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>

      <div className={styles['hero-content']}>
        <h1>Welcome to My World</h1>
        <p>I am Vishnu</p>
        <Link href="/about" className={styles['hero-btn']}>
          More about me
        </Link>
      </div>
    </div>
  );
}
