// vishlabs-client/src/components/Footer.tsx
import Link from "next/link";
import styles from "./Footer.module.scss";

export default function Footer() {
  return (
    <footer className={styles["custom-footer"]}>
      <div className={styles["footer-logo"]}>
        <Link href="/">
          <img src="/images/VG_logo.png" alt="Logo" className={styles.logo} />
        </Link>
      </div>
      <div className={styles["footer-text"]}>
        <p>© 2026 VG. All rights reserved.</p>
      </div>
      <div className={styles["footer-icons"]}>
        <a
          href="https://linkedin.com/in/vishnugops"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="LinkedIn"
        >
          <i className="fab fa-linkedin"></i>
        </a>
        <a
          href="https://github.com/vishnuGops"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Github"
        >
          <i className="fab fa-github"></i>
        </a>
        <a
          href="https://instagram.com/vishnugops"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Instagram"
        >
          <i className="fab fa-instagram"></i>
        </a>
        <a
          href="https://www.youtube.com/channel/UCqRp3VPHZ_sW4Rxkd2Rx51A"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="YouTube"
        >
          <i className="fab fa-youtube"></i>
        </a>
      </div>
    </footer>
  );
}

// dashboard-client/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone : true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {

}

<footer class="custom-footer">
  <div class="footer-logo">
    <a routerLink="/">
      <img src="/images/VG_logo.png" alt="Logo" class="logo" />
    </a>
  </div>
  <div class="footer-text">
    <p>© 2025 VG. All rights reserved.</p>
  </div>
  <div class="footer-icons">
    <a
      href="https://instagram.com/vishnugops"
      target="_blank"
      rel="noopener"
      aria-label="Instagram"
    >
      <i class="fab fa-instagram"></i>
    </a>
    <a
      href="https://www.youtube.com/channel/UCqRp3VPHZ_sW4Rxkd2Rx51A"
      target="_blank"
      rel="noopener"
      aria-label="YouTube"
    >
      <i class="fab fa-youtube"></i>
    </a>
    <a
      href="https://x.com/vishnu_gops"
      target="_blank"
      rel="noopener"
      aria-label="Twitter"
    >
      <i class="fab fa-twitter"></i>
    </a>
    <a
      href="https://linkedin.com/in/vishnugops"
      target="_blank"
      rel="noopener"
      aria-label="LinkedIn"
    >
      <i class="fab fa-linkedin"></i>
    </a>
  </div>
</footer>
