// vishlabs-client/src/components/Navbar.tsx
import Link from 'next/link';
import styles from './Navbar.module.scss';

export default function Navbar() {
  return (
    <div className={styles['custom-toolbar']}>
      <div className={styles['navbar-logo']}>
        <Link href="/">
          <img src="/images/VG_logo.png" alt="Logo" className={styles.logo} />
        </Link>
      </div>
      <span className={styles.spacer}></span>
      <nav>
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/projects">Projects</Link>
        <Link href="/contact">Contact</Link>
      </nav>
    </div>
  );
}

// dashboard-client/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  standalone : true,
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss'
})
export class NavbarComponent {

}

<mat-toolbar class="custom-toolbar">
  <div class="navbar-logo">
    <a routerLink="/">
      <img src="/images/VG_logo.png" alt="Logo" class="logo" />
    </a>
  </div>
  <span class="spacer"></span>
  <nav>
    <a mat-button routerLink="/">Home</a>
    <a mat-button routerLink="/about">About</a>
    <a mat-button routerLink="/projects">Projects</a>
    <a mat-button routerLink="/contact">Contact</a>
  </nav>
</mat-toolbar>
